// frontend/React/src/tic-toe-observable/src/components/TicToeBoard/TicToeCell.tsx
import React, { MouseEvent } from 'react';
import { TicToeCellSate } from '../../shared/models/ticToe.model';

/** TicToc cell's click handler */
export type TicToeCellClickHandler = (rowIndex: number, columnIndex: number) => void;

interface TicToeCellProps {
	columnIndex	: number;
	rowIndex	: number;
	width?		: number;
	state		: TicToeCellSate;
	onClick?	: TicToeCellClickHandler; 
}

const TicToeCell: React.FC<TicToeCellProps> = (props: TicToeCellProps) => {
	/** Render cell state */
	const renderCellState = (): string => {
		switch (props.state) {
			case TicToeCellSate.Empty:
			default:
				return ' ';
			case TicToeCellSate.X:
				return 'X';
			case TicToeCellSate.O:
				return 'O';
		}
	};

	/** Cell click handler */
	const clickHandler = (event: MouseEvent<HTMLButtonElement>): void => {
		props.onClick?.(props.rowIndex, props.columnIndex);
	};

	// Cell style for props' values
	const cellStyle = {
		width			: `${props.width || 20}px`,
		height			: `${props.width || 20}px`,
		verticalAlign	: "top"
	};

	return (
		<button style={cellStyle} onClick={clickHandler} title="ciao">
			{renderCellState()}
		</button>
	);
}

export default TicToeCell;

// frontend/Angular/src/tic-toe/src/tic-toe/tic-toe-cell/tic-toe-cell.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { TicToeCellSate } from '../../../../../../shared/models/ticToe.model';

/** Data of onClick event */
export interface TicToeCellOnClick {
	rowIndex	: number;
	columnIndex	: number;
}

@Component({
	selector: 'tic-toe-cell',
	templateUrl: './tic-toe-cell.component.html',
	styleUrls: ['./tic-toe-cell.component.scss']
})
export class TicToeCellComponent {
	/** Size of cell, default value is 20px */
	@Input() public cellWidth: number = 20;

	/** Row index, value must be passed */
	@Input() public rowIndex!: number;
	/** Column index, value must be passed */
	@Input() public columnIndex!: number;
	/** State of the cell, default state is Empty */
	@Input() public cellState: TicToeCellSate = TicToeCellSate.Empty;

	/** On user click on button event */
	@Output() public cellClick: EventEmitter<TicToeCellOnClick> = new EventEmitter<TicToeCellOnClick>();

	/** Handle click on the button */
	public onClickHandler(): void {
		this.cellClick.emit(<TicToeCellOnClick> {
			rowIndex	: this.rowIndex,
			columnIndex	: this.columnIndex
		});
	}

	/** Render cell state */
	public renderCellState(): string {
		switch (this.cellState) {
			case TicToeCellSate.Empty:
			default:
				return ' ';
			case TicToeCellSate.X:
				return 'X';
			case TicToeCellSate.O:
				return 'O';
		}
	};
}

<button type="button" [ngStyle]="{'width.px': cellWidth, 'height.px': cellWidth}" (click)="onClickHandler()" title="Cell">
	{{renderCellState()}}
</button>
