// frontend/React/src/tic-toe/src/components/TicToeDisplay/TicToeDisplay.tsx
import React from 'react';
import { PlayerToPlay } from '../../shared/models/ticToe.model';

interface TicToeDisplayProps {
	isGameActive	: boolean;
	playerToPlay	: PlayerToPlay;
	playerWon		: PlayerToPlay | null;
	onRestart?		: () => void;
}

const TicToeDisplay: React.FC<TicToeDisplayProps> = (props: TicToeDisplayProps) => {
	/** Return the name of the player */
	const playerToName = (player: PlayerToPlay): string => {
		switch (player) {
			case PlayerToPlay.PlayerX:
				return "X";
			case PlayerToPlay.PlayerO:
				return "O";
			default:
				return "";
		}
	};

	/** Handle restart request */
	const onRestartHandler = (): void => {
		props.onRestart?.();
	};

	return (<>
		{props.isGameActive &&
			<h4>Turn of player {playerToName(props.playerToPlay)}</h4>
		}
		{props.playerWon != null &&
			<h4>Player {playerToName(props.playerWon)} won</h4>
		}
		{/* <button onClick={onRestartHandler}>Restart</button> */}
	</>);
}

export default TicToeDisplay;

// frontend/Angular/src/tic-toe/src/tic-toe/tic-toe-display/tic-toe-display.component.ts
import { Component } from '@angular/core';
import { TicToeGameService } from '../../services/tic-toe.service';
import { PlayerToPlay } from '../../../../../../shared/models/ticToe.model';

@Component({
	selector: 'tic-toe-display',
	templateUrl: './tic-toe-display.component.html',
	styleUrls: ['./tic-toe-display.component.scss']
})
export class TicToeDisplayComponent {
	/** Service for the game */
	public ticToeGameService: TicToeGameService;

	constructor(ticToeGameService: TicToeGameService) {
		this.ticToeGameService = ticToeGameService;
	}

	/** Return the name of the player */
	public playerToName(player: PlayerToPlay | null): string {
		switch (player) {
			case PlayerToPlay.PlayerX:
				return "X";
			case PlayerToPlay.PlayerO:
				return "O";
			default:
				return "";
		}
	}

	/** Handle restart request */
	public onRestartHandler(): void{
		this.ticToeGameService.resetBoard();
	};
}

<h4 *ngIf="ticToeGameService.isGameActive$ | async">
	Turn of player {{ playerToName(ticToeGameService.player$ | async) }}
</h4>
<h4 *ngIf="ticToeGameService.playerWon$ | async as whoWon">
	Player {{ playerToName(whoWon) }} won
</h4>
<button (click)="onRestartHandler()">Restart</button>
