// frontend/React/src/tic-toe-redux/src/components/TicToeBoard/TicToeBoard.tsx
import React, { useContext } from 'react';
import { useSelector } from 'react-redux';
import * as GameSelectors from '../../redux/game.selectors';
import { gameStore } from '../../redux/game.store';
import { useStorePropChange } from '../../redux/utility';
import { TicToeGameReduxService, TicToeGameReduxServiceContext } from '../../services/tic-toe-redux.service';
import { PlayerToPlay } from '../../shared/models/ticToe.model';
import TicToeCell, { TicToeCellClickHandler } from './TicToeCell';

// Component style
import './TicToeBoard.scss';

interface TicToeBoardProps {
	/** Callback when somebody won */
	onWon?: (player: PlayerToPlay) => void;
	/** On player changed */
	onPlayerChanged?: (player: PlayerToPlay) => void;
	/** On active game state changed */
	onIsGameActiveChanged?: (isGameActive: boolean) => void;
}

const TicToeBoard: React.FC<TicToeBoardProps> = (props: TicToeBoardProps) => {
	/** Size of cells */
	const cellWidth: number = 30;

	/** Service for the game */
	const _ticToeGameService: TicToeGameReduxService = useContext(TicToeGameReduxServiceContext);
	/** Activation of the game, used for game ended or waiting */
	const isGameActiveRef: React.MutableRefObject<boolean | undefined> = useStorePropChange(gameStore, GameSelectors.selectIsGameActive);

	/** Cell click handler */
	const cellClickHandler: TicToeCellClickHandler = (rowIndex: number, columnIndex: number): void => {
		// Check game is active
		if (!isGameActiveRef.current) {
			console.warn("Game not active");
			return ;
		}

		// Check cell can change
		if (!_ticToeGameService.canCellChange(rowIndex, columnIndex)) {
			console.warn("Not empty cell");
			return ;
		}

		// Set cell played
		_ticToeGameService.playerPlayed(
			/* rowIndex */		rowIndex,
			/* columnIndex */	columnIndex
		);
	};

	// Subscribe to re-render component on board change
	useSelector(GameSelectors.selectBoard);

	console.info("TicToeBoard render");

	return (<>
		<div className="cells-row">
			<TicToeCell rowIndex={0} columnIndex={0} width={cellWidth} state={_ticToeGameService.getCellState(0, 0)} onClick={cellClickHandler} />
			<TicToeCell rowIndex={0} columnIndex={1} width={cellWidth} state={_ticToeGameService.getCellState(0, 1)} onClick={cellClickHandler} />
			<TicToeCell rowIndex={0} columnIndex={2} width={cellWidth} state={_ticToeGameService.getCellState(0, 2)} onClick={cellClickHandler} />
		</div>
		<div className="cells-row">
			<TicToeCell rowIndex={1} columnIndex={0} width={cellWidth} state={_ticToeGameService.getCellState(1, 0)} onClick={cellClickHandler} />
			<TicToeCell rowIndex={1} columnIndex={1} width={cellWidth} state={_ticToeGameService.getCellState(1, 1)} onClick={cellClickHandler} />
			<TicToeCell rowIndex={1} columnIndex={2} width={cellWidth} state={_ticToeGameService.getCellState(1, 2)} onClick={cellClickHandler} />
		</div>
		<div className="cells-row">
			<TicToeCell rowIndex={2} columnIndex={0} width={cellWidth} state={_ticToeGameService.getCellState(2, 0)} onClick={cellClickHandler} />
			<TicToeCell rowIndex={2} columnIndex={1} width={cellWidth} state={_ticToeGameService.getCellState(2, 1)} onClick={cellClickHandler} />
			<TicToeCell rowIndex={2} columnIndex={2} width={cellWidth} state={_ticToeGameService.getCellState(2, 2)} onClick={cellClickHandler} />
		</div>
	</>);
};

export default TicToeBoard;

// frontend/Angular/src/tic-toe/src/tic-toe/tic-toe-board/tic-toe-board.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { TicToeGameService } from '../../services/tic-toe.service';
import { TicToeBoardCells, TicToeCellSate } from '../../models/ticToe.model';
import { TicToeCellOnClick } from '../tic-toe-cell/tic-toe-cell.component';
import { Subscription } from 'rxjs';

@Component({
	selector: 'tic-toe-board',
	templateUrl: './tic-toe-board.component.html',
	styleUrls: ['./tic-toe-board.component.scss']
})
export class TicToeBoardComponent implements OnInit, OnDestroy {
	private _unSubscription: Subscription = new Subscription();

	/** Active state of the game */
	private _isGameActive: boolean = true;

	/** Size of cells */
	public cellWidth: number = 30;
	/** Service for the game */
	public ticToeGameService: TicToeGameService;

	constructor(ticToeGameService: TicToeGameService) {
		this.ticToeGameService = ticToeGameService;
	}

	ngOnInit(): void {
		// Register active game state change
		this._unSubscription.add(
			this.ticToeGameService.isGameActive$.subscribe((isGameActive: boolean) => {
				this._isGameActive = isGameActive;
			})
		);
	}

	ngOnDestroy(): void {
		this._unSubscription.unsubscribe();
	}

	/** Handle click on the button */
	public onClickHandler(params: TicToeCellOnClick): void {
		// Check game is active
		if (!this._isGameActive) {
			console.warn("Game not active");
			return ;
		}

		// Check cell can change
		if (!this.ticToeGameService.canCellChange(params.rowIndex, params.columnIndex)) {
			console.warn("Not empty cell");
			return ;
		}

		// Set cell played
		this.ticToeGameService.playerPlayed(
			params.rowIndex,
			params.columnIndex
		);
	}
}

<div class="cells-row">
	<tic-toe-cell [rowIndex]="0" [columnIndex]="0" [cellWidth]="cellWidth" (cellClick)="onClickHandler($event)" [cellState]="ticToeGameService.getCellState(0, 0)"></tic-toe-cell>
	<tic-toe-cell [rowIndex]="0" [columnIndex]="1" [cellWidth]="cellWidth" (cellClick)="onClickHandler($event)" [cellState]="ticToeGameService.getCellState(0, 1)"></tic-toe-cell>
	<tic-toe-cell [rowIndex]="0" [columnIndex]="2" [cellWidth]="cellWidth" (cellClick)="onClickHandler($event)" [cellState]="ticToeGameService.getCellState(0, 2)"></tic-toe-cell>
</div>
<div class="cells-row">
	<tic-toe-cell [rowIndex]="1" [columnIndex]="0" [cellWidth]="cellWidth" (cellClick)="onClickHandler($event)" [cellState]="ticToeGameService.getCellState(1, 0)"></tic-toe-cell>
	<tic-toe-cell [rowIndex]="1" [columnIndex]="1" [cellWidth]="cellWidth" (cellClick)="onClickHandler($event)" [cellState]="ticToeGameService.getCellState(1, 1)"></tic-toe-cell>
	<tic-toe-cell [rowIndex]="1" [columnIndex]="2" [cellWidth]="cellWidth" (cellClick)="onClickHandler($event)" [cellState]="ticToeGameService.getCellState(1, 2)"></tic-toe-cell>
</div>
<div class="cells-row">
	<tic-toe-cell [rowIndex]="2" [columnIndex]="0" [cellWidth]="cellWidth" (cellClick)="onClickHandler($event)" [cellState]="ticToeGameService.getCellState(2, 0)"></tic-toe-cell>
	<tic-toe-cell [rowIndex]="2" [columnIndex]="1" [cellWidth]="cellWidth" (cellClick)="onClickHandler($event)" [cellState]="ticToeGameService.getCellState(2, 1)"></tic-toe-cell>
	<tic-toe-cell [rowIndex]="2" [columnIndex]="2" [cellWidth]="cellWidth" (cellClick)="onClickHandler($event)" [cellState]="ticToeGameService.getCellState(2, 2)"></tic-toe-cell>
</div>
