// frontend/React/src/tic-toe-observable/src/components/TicToeDisplay/TicToeDisplayStatus.tsx
import React, { useContext } from 'react';
import { useObservableState } from 'observable-hooks';
import { TicToeGameObservableService, TicToeGameObservableServiceContext } from '../../services/tic-toe-observable.service';

const TicToeDisplayStatus: React.FC = () => {
	/** Service for the game */
	const _ticToeGameService: TicToeGameObservableService = useContext(TicToeGameObservableServiceContext);

	/** Active state of the game */
	const isGameActive	: boolean | undefined = useObservableState(_ticToeGameService.isGameActive$);

	console.info("TicToeDisplayStatus render")

	return (<>
		Game state: {isGameActive ? "active" : "not active"}
	</>);
};

export default TicToeDisplayStatus;

// frontend/Angular/src/tic-toe/src/tic-toe/tic-toe-display-status/tic-toe-display-status.component.ts
import { Component } from '@angular/core';
import { TicToeGameService } from '../../services/tic-toe.service';

@Component({
	selector: 'tic-toe-display-status',
	templateUrl: './tic-toe-display-status.component.html',
	styleUrls: ['./tic-toe-display-status.component.scss']
})
export class TicToeDisplayStatusComponent {
	/** Service for the game */
	public ticToeGameService: TicToeGameService;

	constructor(ticToeGameService: TicToeGameService) {
		this.ticToeGameService = ticToeGameService;
	}
}

Game state: 
<span *ngIf="ticToeGameService.isGameActive$ | async">active</span>
<span *ngIf="!(ticToeGameService.isGameActive$ | async)">not active</span>
